version: 2.1

jobs:
    build-and-test:
        docker:
            - image: cimg/node:14.17
        parallelism: 5
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Run Tests
                  command: npm test -- --ci --reporters=default --reporters=jest-junit --testLocationInResults --outputFile=test-results/junit.xml --runInBand --findRelatedTests $(circleci tests glob "tests/**/*.test.js" | circleci tests split --split-by=timings)
            - store_artifacts:
                  path: tests/test-results
                  destination: tests/test-results
            - store_test_results:
                  path: tests/test-results

workflows:
    version: 2
    build-and-test-workflow:
        jobs:
            - build-and-test
