# .circleci/config.yml

version: 2.1

executors:
    node-executor:
        docker:
            - image: cimg/node:18.16.0 # Specify the Node.js version you need

jobs:
    build-and-test:
        executor: node-executor
        steps:
            - checkout

            # Restore cached dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            # Install dependencies
            - run:
                  name: Install Dependencies
                  command: npm install

            # Save dependencies cache
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            # Run lint
            - run:
                  name: Lint Code
                  command: npm run lint

            # Run tests with coverage
            - run:
                  name: Run Tests
                  command: npm test

            # Store test results
            - store_test_results:
                  path: coverage

            # Store coverage reports
            - store_artifacts:
                  path: coverage
                  destination: coverage
workflows:
    version: 2
    build_and_test_workflow:
        jobs:
            - build-and-test
