version: 2.1

jobs:
    build-and-test:
        docker:
            - image: cimg/node:22.10.0-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                  name: Run Tests
                  command: |
                      npm run build
                      npm test -- --ci --reporters=default --reporters=jest-junit
            - store_artifacts:
                  path: test-results
                  destination: test-results
            - store_test_results:
                  path: test-results

workflows:
    version: 2
    build-and-test-workflow:
        jobs:
            - build-and-test
